// packages/vue/src/theme/ThemeProvider.vue
<script setup lang="ts">
import { computed, inject, onMounted, provide, ref, type InjectionKey } from 'vue';
import type { TraekTheme } from './tokens.js';
import { themes, DEFAULT_THEME } from './themes.js';
import type { ThemeName } from './themes.js';

export interface ThemeContextValue {
	currentTheme: TraekTheme;
	currentThemeName: ThemeName;
	setTheme: (name: ThemeName) => void;
	applyTheme: (theme: TraekTheme) => void;
}

export const THEME_KEY: InjectionKey<ThemeContextValue> = Symbol('traek-theme');

export interface ThemeProviderProps {
	initialTheme?: ThemeName;
}

const props = withDefaults(defineProps<ThemeProviderProps>(), {
	initialTheme: () => DEFAULT_THEME
});

const currentThemeName = ref<ThemeName>(props.initialTheme);
const currentTheme = ref<TraekTheme>(themes[props.initialTheme] ?? themes[DEFAULT_THEME]);

function applyThemeToRoot(theme: TraekTheme, themeName?: ThemeName): void {
	if (typeof document === 'undefined') return;
	const root = document.documentElement;
	if (themeName) root.setAttribute('data-theme', themeName);

	const c = theme.colors;
	root.style.setProperty('--traek-canvas-bg', c.canvasBg);
	root.style.setProperty('--traek-canvas-dot', c.canvasDot);
	root.style.setProperty('--traek-node-bg', c.nodeBg);
	root.style.setProperty('--traek-node-border', c.nodeBorder);
	root.style.setProperty('--traek-node-text', c.nodeText);
	root.style.setProperty('--traek-node-active-border', c.nodeActiveBorder);
	root.style.setProperty('--traek-node-active-glow', c.nodeActiveGlow);
	root.style.setProperty('--traek-node-user-border-top', c.nodeUserBorderTop);
	root.style.setProperty('--traek-node-assistant-border-top', c.nodeAssistantBorderTop);
	root.style.setProperty('--traek-connection-stroke', c.connectionStroke);
	root.style.setProperty('--traek-connection-highlight', c.connectionHighlight);
	root.style.setProperty('--traek-input-bg', c.inputBg);
	root.style.setProperty('--traek-input-border', c.inputBorder);
	root.style.setProperty('--traek-input-shadow', c.inputShadow);
	root.style.setProperty('--traek-input-button-bg', c.inputButtonBg);
	root.style.setProperty('--traek-input-button-text', c.inputButtonText);
	root.style.setProperty('--traek-input-text', c.inputText);
	root.style.setProperty('--traek-input-context-bg', c.inputContextBg);
	root.style.setProperty('--traek-input-context-text', c.inputContextText);
	root.style.setProperty('--traek-input-dot', c.inputDot);
	root.style.setProperty('--traek-input-dot-muted', c.inputDotMuted);
	root.style.setProperty('--traek-stats-text', c.statsText);
	root.style.setProperty('--traek-textnode-text', c.textNodeText);
	root.style.setProperty('--traek-textnode-bg', c.textNodeBg);
	root.style.setProperty('--traek-markdown-quote-border', c.markdownQuoteBorder);
	root.style.setProperty('--traek-markdown-quote-text', c.markdownQuoteText);
	root.style.setProperty('--traek-markdown-hr', c.markdownHr);
	root.style.setProperty('--traek-scroll-hint-bg', c.scrollHintBg);
	root.style.setProperty('--traek-scroll-hint-text', c.scrollHintText);
	root.style.setProperty('--traek-scrollbar-thumb', c.scrollbarThumb);
	root.style.setProperty('--traek-scrollbar-thumb-hover', c.scrollbarThumbHover);
	root.style.setProperty('--traek-typing-cursor', c.typingCursor);
	root.style.setProperty('--traek-search-match-border', c.searchMatchBorder);
	root.style.setProperty('--traek-search-dimmed-opacity', c.searchDimmedOpacity.toString());
	root.style.setProperty('--traek-thought-panel-bg', c.thoughtPanelBg);
	root.style.setProperty('--traek-thought-panel-border', c.thoughtPanelBorder);
	root.style.setProperty('--traek-thought-panel-border-active', c.thoughtPanelBorderActive);
	root.style.setProperty('--traek-thought-panel-glow', c.thoughtPanelGlow);
	root.style.setProperty('--traek-thought-header-bg', c.thoughtHeaderBg);
	root.style.setProperty('--traek-thought-header-border', c.thoughtHeaderBorder);
	root.style.setProperty('--traek-thought-header-muted', c.thoughtHeaderMuted);
	root.style.setProperty('--traek-thought-header-accent', c.thoughtHeaderAccent);
	root.style.setProperty('--traek-thought-tag-cyan', c.thoughtTagCyan);
	root.style.setProperty('--traek-thought-tag-orange', c.thoughtTagOrange);
	root.style.setProperty('--traek-thought-tag-gray', c.thoughtTagGray);
	root.style.setProperty('--traek-thought-divider', c.thoughtDivider);
	root.style.setProperty('--traek-thought-row-bg', c.thoughtRowBg);
	root.style.setProperty('--traek-thought-row-muted-1', c.thoughtRowMuted1);
	root.style.setProperty('--traek-thought-row-muted-2', c.thoughtRowMuted2);
	root.style.setProperty('--traek-thought-row-muted-3', c.thoughtRowMuted3);
	root.style.setProperty('--traek-thought-row-muted-4', c.thoughtRowMuted4);
	root.style.setProperty('--traek-thought-badge-cyan', c.thoughtBadgeCyan);
	root.style.setProperty('--traek-thought-footer-muted', c.thoughtFooterMuted);
	root.style.setProperty('--traek-thought-footer-bg', c.thoughtFooterBg);
	root.style.setProperty('--traek-thought-footer-border', c.thoughtFooterBorder);
	root.style.setProperty('--traek-thought-toggle-bg', c.thoughtToggleBg);
	root.style.setProperty('--traek-thought-toggle-border', c.thoughtToggleBorder);
	root.style.setProperty('--traek-overlay-gradient-1', c.overlayGradient1);
	root.style.setProperty('--traek-overlay-gradient-2', c.overlayGradient2);
	root.style.setProperty('--traek-overlay-gradient-3', c.overlayGradient3);
	root.style.setProperty('--traek-overlay-card-bg', c.overlayCardBg);
	root.style.setProperty('--traek-overlay-card-border', c.overlayCardBorder);
	root.style.setProperty('--traek-overlay-card-shadow', c.overlayCardShadow);
	root.style.setProperty('--traek-overlay-text', c.overlayText);
	root.style.setProperty('--traek-overlay-pill-bg', c.overlayPillBg);
	root.style.setProperty('--traek-overlay-pill-shadow', c.overlayPillShadow);

	const s = theme.spacing;
	root.style.setProperty('--traek-spacing-xs', `${s.xs}px`);
	root.style.setProperty('--traek-spacing-sm', `${s.sm}px`);
	root.style.setProperty('--traek-spacing-md', `${s.md}px`);
	root.style.setProperty('--traek-spacing-lg', `${s.lg}px`);
	root.style.setProperty('--traek-spacing-xl', `${s.xl}px`);

	const rad = theme.radius;
	root.style.setProperty('--traek-radius-sm', `${rad.sm}px`);
	root.style.setProperty('--traek-radius-md', `${rad.md}px`);
	root.style.setProperty('--traek-radius-lg', `${rad.lg}px`);

	const typ = theme.typography;
	root.style.setProperty('--traek-font-family', typ.fontFamily);
	root.style.setProperty('--traek-font-mono', typ.fontMono);

	const anim = theme.animation;
	root.style.setProperty('--traek-anim-fast', `${anim.fast}ms`);
	root.style.setProperty('--traek-anim-normal', `${anim.normal}ms`);
	root.style.setProperty('--traek-anim-slow', `${anim.slow}ms`);
}

const setTheme = (name: ThemeName) => {
	const t = themes[name];
	if (!t) {
		console.warn(`Theme "${name}" not found, falling back to default`);
		return;
	}
	currentThemeName.value = name;
	currentTheme.value = t;
	applyThemeToRoot(t, name);
};

const applyTheme = (theme: TraekTheme) => {
	currentTheme.value = theme;
	applyThemeToRoot(theme);
};

const context = computed<ThemeContextValue>(() => ({
	currentTheme: currentTheme.value,
	currentThemeName: currentThemeName.value,
	setTheme,
	applyTheme
}));

provide(THEME_KEY, context.value);

onMounted(() => {
	applyThemeToRoot(currentTheme.value, currentThemeName.value);
});
</script>

<template>
	<slot />
</template>

// src/lib/theme/ThemeProvider.svelte
<script lang="ts" module>
	import { setContext, getContext } from 'svelte';
	import type { TraekTheme } from './tokens';
	import type { ThemeName } from './themes';
	import { themes, DEFAULT_THEME } from './themes';

	const THEME_CONTEXT_KEY = Symbol('traek-theme');

	export interface ThemeContext {
		currentTheme: () => TraekTheme;
		currentThemeName: () => ThemeName;
		setTheme: (themeName: ThemeName) => void;
		applyTheme: (theme: TraekTheme) => void;
	}

	/**
	 * Get the theme context from the nearest ThemeProvider ancestor
	 */
	export function useTheme(): ThemeContext {
		const context = getContext<ThemeContext>(THEME_CONTEXT_KEY);
		if (!context) {
			throw new Error('useTheme must be called within a ThemeProvider');
		}
		return context;
	}

	/**
	 * Apply a theme by setting CSS custom properties on :root
	 */
	export function applyThemeToRoot(theme: TraekTheme): void {
		if (typeof document === 'undefined') return;

		const root = document.documentElement;

		// Colors
		root.style.setProperty('--traek-canvas-bg', theme.colors.canvasBg);
		root.style.setProperty('--traek-canvas-dot', theme.colors.canvasDot);
		root.style.setProperty('--traek-node-bg', theme.colors.nodeBg);
		root.style.setProperty('--traek-node-border', theme.colors.nodeBorder);
		root.style.setProperty('--traek-node-text', theme.colors.nodeText);
		root.style.setProperty('--traek-node-active-border', theme.colors.nodeActiveBorder);
		root.style.setProperty('--traek-node-active-glow', theme.colors.nodeActiveGlow);
		root.style.setProperty('--traek-node-user-border-top', theme.colors.nodeUserBorderTop);
		root.style.setProperty(
			'--traek-node-assistant-border-top',
			theme.colors.nodeAssistantBorderTop
		);
		root.style.setProperty('--traek-connection-stroke', theme.colors.connectionStroke);
		root.style.setProperty('--traek-connection-highlight', theme.colors.connectionHighlight);
		root.style.setProperty('--traek-input-bg', theme.colors.inputBg);
		root.style.setProperty('--traek-input-border', theme.colors.inputBorder);
		root.style.setProperty('--traek-input-shadow', theme.colors.inputShadow);
		root.style.setProperty('--traek-input-button-bg', theme.colors.inputButtonBg);
		root.style.setProperty('--traek-input-button-text', theme.colors.inputButtonText);
		root.style.setProperty('--traek-input-text', theme.colors.inputText);
		root.style.setProperty('--traek-input-context-bg', theme.colors.inputContextBg);
		root.style.setProperty('--traek-input-context-text', theme.colors.inputContextText);
		root.style.setProperty('--traek-input-dot', theme.colors.inputDot);
		root.style.setProperty('--traek-input-dot-muted', theme.colors.inputDotMuted);
		root.style.setProperty('--traek-stats-text', theme.colors.statsText);
		root.style.setProperty('--traek-textnode-text', theme.colors.textNodeText);
		root.style.setProperty('--traek-textnode-bg', theme.colors.textNodeBg);
		root.style.setProperty('--traek-markdown-quote-border', theme.colors.markdownQuoteBorder);
		root.style.setProperty('--traek-markdown-quote-text', theme.colors.markdownQuoteText);
		root.style.setProperty('--traek-markdown-hr', theme.colors.markdownHr);
		root.style.setProperty('--traek-scroll-hint-bg', theme.colors.scrollHintBg);
		root.style.setProperty('--traek-scroll-hint-text', theme.colors.scrollHintText);
		root.style.setProperty('--traek-scrollbar-thumb', theme.colors.scrollbarThumb);
		root.style.setProperty('--traek-scrollbar-thumb-hover', theme.colors.scrollbarThumbHover);
		root.style.setProperty('--traek-typing-cursor', theme.colors.typingCursor);
		root.style.setProperty('--traek-search-match-border', theme.colors.searchMatchBorder);
		root.style.setProperty(
			'--traek-search-dimmed-opacity',
			theme.colors.searchDimmedOpacity.toString()
		);
		root.style.setProperty('--traek-thought-panel-bg', theme.colors.thoughtPanelBg);
		root.style.setProperty('--traek-thought-panel-border', theme.colors.thoughtPanelBorder);
		root.style.setProperty(
			'--traek-thought-panel-border-active',
			theme.colors.thoughtPanelBorderActive
		);
		root.style.setProperty('--traek-thought-panel-glow', theme.colors.thoughtPanelGlow);
		root.style.setProperty('--traek-thought-header-bg', theme.colors.thoughtHeaderBg);
		root.style.setProperty('--traek-thought-header-border', theme.colors.thoughtHeaderBorder);
		root.style.setProperty('--traek-thought-header-muted', theme.colors.thoughtHeaderMuted);
		root.style.setProperty('--traek-thought-header-accent', theme.colors.thoughtHeaderAccent);
		root.style.setProperty('--traek-thought-tag-cyan', theme.colors.thoughtTagCyan);
		root.style.setProperty('--traek-thought-tag-orange', theme.colors.thoughtTagOrange);
		root.style.setProperty('--traek-thought-tag-gray', theme.colors.thoughtTagGray);
		root.style.setProperty('--traek-thought-divider', theme.colors.thoughtDivider);
		root.style.setProperty('--traek-thought-row-bg', theme.colors.thoughtRowBg);
		root.style.setProperty('--traek-thought-row-muted-1', theme.colors.thoughtRowMuted1);
		root.style.setProperty('--traek-thought-row-muted-2', theme.colors.thoughtRowMuted2);
		root.style.setProperty('--traek-thought-row-muted-3', theme.colors.thoughtRowMuted3);
		root.style.setProperty('--traek-thought-row-muted-4', theme.colors.thoughtRowMuted4);
		root.style.setProperty('--traek-thought-badge-cyan', theme.colors.thoughtBadgeCyan);
		root.style.setProperty('--traek-thought-footer-muted', theme.colors.thoughtFooterMuted);
		root.style.setProperty('--traek-thought-footer-bg', theme.colors.thoughtFooterBg);
		root.style.setProperty('--traek-thought-footer-border', theme.colors.thoughtFooterBorder);
		root.style.setProperty('--traek-thought-toggle-bg', theme.colors.thoughtToggleBg);
		root.style.setProperty('--traek-thought-toggle-border', theme.colors.thoughtToggleBorder);
		root.style.setProperty('--traek-overlay-gradient-1', theme.colors.overlayGradient1);
		root.style.setProperty('--traek-overlay-gradient-2', theme.colors.overlayGradient2);
		root.style.setProperty('--traek-overlay-gradient-3', theme.colors.overlayGradient3);
		root.style.setProperty('--traek-overlay-card-bg', theme.colors.overlayCardBg);
		root.style.setProperty('--traek-overlay-card-border', theme.colors.overlayCardBorder);
		root.style.setProperty('--traek-overlay-card-shadow', theme.colors.overlayCardShadow);
		root.style.setProperty('--traek-overlay-text', theme.colors.overlayText);
		root.style.setProperty('--traek-overlay-pill-bg', theme.colors.overlayPillBg);
		root.style.setProperty('--traek-overlay-pill-shadow', theme.colors.overlayPillShadow);
	}
</script>

<script lang="ts">
	import { onMount } from 'svelte';

	let {
		initialTheme = DEFAULT_THEME,
		children
	}: { initialTheme?: ThemeName; children: import('svelte').Snippet } = $props();

	let currentThemeName = $state<ThemeName>(DEFAULT_THEME);
	let currentTheme = $state<TraekTheme>(themes[DEFAULT_THEME]);

	// Initialize theme from props
	$effect(() => {
		if (initialTheme !== currentThemeName) {
			currentThemeName = initialTheme;
			currentTheme = themes[initialTheme];
		}
	});

	/**
	 * Set theme by name
	 */
	function setTheme(themeName: ThemeName): void {
		if (!themes[themeName]) {
			console.warn(`Theme "${themeName}" not found, falling back to default`);
			themeName = DEFAULT_THEME;
		}

		currentThemeName = themeName;
		currentTheme = themes[themeName];
		applyThemeToRoot(currentTheme);
	}

	/**
	 * Apply a custom theme object
	 */
	function applyTheme(theme: TraekTheme): void {
		currentTheme = theme;
		applyThemeToRoot(theme);
	}

	/**
	 * Get current theme object
	 */
	function getCurrentTheme(): TraekTheme {
		return currentTheme;
	}

	/**
	 * Get current theme name
	 */
	function getCurrentThemeName(): ThemeName {
		return currentThemeName;
	}

	// Set up context
	const themeContext: ThemeContext = {
		currentTheme: getCurrentTheme,
		currentThemeName: getCurrentThemeName,
		setTheme,
		applyTheme
	};

	setContext(THEME_CONTEXT_KEY, themeContext);

	// Apply initial theme on mount
	onMount(() => {
		applyThemeToRoot(currentTheme);
	});
</script>

{@render children()}
