// src/lib/tags/TagBadges.svelte
<script lang="ts">
	import type { Node, TraekEngine } from '../TraekEngine.svelte';
	import { getNodeTags, getTagConfig } from './tagUtils';

	let { node, engine }: { node: Node; engine?: TraekEngine } = $props();

	const tags = $derived(getNodeTags(node));

	function handleRemoveTag(tag: string) {
		if (engine) {
			engine.removeTag(node.id, tag);
		}
	}
</script>

{#if tags.length > 0}
	<div class="tag-badges">
		{#each tags as tag (tag)}
			{@const config = getTagConfig(tag)}
			<button
				type="button"
				class="tag-badge"
				style:color={config.color}
				style:background={config.bgColor}
				style:border-color={config.color}
				onclick={(e) => {
					e.stopPropagation();
					handleRemoveTag(tag);
				}}
				title="Click to remove tag"
			>
				<span class="tag-badge-label">{config.label}</span>
				<span class="tag-badge-remove">×</span>
			</button>
		{/each}
	</div>
{/if}

<style>
	.tag-badges {
		display: flex;
		flex-wrap: wrap;
		gap: 4px;
		padding: 6px 14px 8px;
		border-bottom: 1px solid var(--traek-thought-divider, rgba(255, 255, 255, 0.06));
	}

	.tag-badge {
		display: inline-flex;
		align-items: center;
		gap: 4px;
		padding: 3px 8px;
		border: 1px solid;
		border-radius: 999px;
		font-size: 10px;
		font-weight: 500;
		letter-spacing: 0.3px;
		cursor: pointer;
		transition:
			opacity 0.15s,
			transform 0.15s;
		text-transform: uppercase;
	}

	.tag-badge:hover {
		opacity: 0.8;
		transform: scale(1.05);
	}

	.tag-badge:focus-visible {
		outline: 2px solid var(--traek-input-button-bg, #00d8ff);
		outline-offset: 2px;
	}

	.tag-badge-label {
		line-height: 1;
	}

	.tag-badge-remove {
		font-size: 14px;
		line-height: 1;
		opacity: 0.7;
	}

	.tag-badge:hover .tag-badge-remove {
		opacity: 1;
	}
</style>

// packages/vue/src/tags/TagBadges.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { TraekEngine } from '@traek/core';
import { getNodeTags, getTagConfig } from './tagUtils.js';

export interface TagBadgesProps {
	nodeId: string;
	engine: TraekEngine;
	editable?: boolean;
}

const props = withDefaults(defineProps<TagBadgesProps>(), {
	editable: false
});

const tags = computed(() => {
	const node = props.engine.getNode(props.nodeId);
	return node ? getNodeTags(node) : [];
});

function removeTag(tag: string) {
	const node = props.engine.getNode(props.nodeId);
	if (!node) return;
	const current = getNodeTags(node).filter((t) => t !== tag);
	props.engine.updateNode(props.nodeId, {
		metadata: { x: 0, y: 0, ...node.metadata, tags: current }
	});
}
</script>

<template>
	<div v-if="tags.length > 0" :style="{ display: 'flex', flexWrap: 'wrap', gap: '4px' }">
		<span
			v-for="tag in tags"
			:key="tag"
			:style="{
				display: 'inline-flex',
				alignItems: 'center',
				gap: '4px',
				padding: '2px 8px',
				borderRadius: '12px',
				fontSize: '11px',
				fontWeight: 500,
				color: getTagConfig(tag).color,
				background: getTagConfig(tag).bgColor,
				border: `1px solid ${getTagConfig(tag).color}33`
			}"
		>
			{{ getTagConfig(tag).label }}
			<button
				v-if="editable"
				@click.stop="removeTag(tag)"
				:aria-label="`Remove ${getTagConfig(tag).label} tag`"
				:style="{
					background: 'transparent',
					border: 'none',
					color: 'inherit',
					cursor: 'pointer',
					padding: 0,
					lineHeight: 1,
					fontSize: '12px',
					opacity: 0.7
				}"
			>
				×
			</button>
		</span>
	</div>
</template>
