// packages/sdk/src/tags/TagDropdown.svelte
<script lang="ts">
	import { slide } from 'svelte/transition';
	import type { Node, TraekEngine } from '../TraekEngine.svelte';
	import { PREDEFINED_TAGS, getNodeTags } from './tagUtils';

	let { node, engine, onClose }: { node: Node; engine: TraekEngine; onClose?: () => void } =
		$props();

	let isOpen = $state(false);
	let customTagInput = $state('');

	const nodeTags = $derived(getNodeTags(node));

	function toggleDropdown() {
		isOpen = !isOpen;
	}

	function handleAddTag(tag: string) {
		engine.addTag(node.id, tag);
	}

	function handleRemoveTag(tag: string) {
		engine.removeTag(node.id, tag);
	}

	function handleToggleTag(tag: string) {
		if (nodeTags.includes(tag)) {
			handleRemoveTag(tag);
		} else {
			handleAddTag(tag);
		}
	}

	function handleAddCustomTag() {
		const tag = customTagInput.trim().toLowerCase();
		if (tag && !nodeTags.includes(tag)) {
			handleAddTag(tag);
			customTagInput = '';
		}
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Enter') {
			e.preventDefault();
			handleAddCustomTag();
		} else if (e.key === 'Escape') {
			isOpen = false;
			onClose?.();
		}
	}

	function handleBackdropClick() {
		isOpen = false;
		onClose?.();
	}
</script>

<svelte:window
	onkeydown={(e) => {
		if (e.key === 'Escape' && isOpen) {
			handleBackdropClick();
		}
	}}
/>

{#if isOpen}
	<div
		class="tag-dropdown-backdrop"
		role="presentation"
		tabindex="-1"
		onclick={handleBackdropClick}
	></div>
{/if}

<div class="tag-dropdown-container">
	<button
		type="button"
		class="tag-dropdown-trigger"
		onclick={toggleDropdown}
		title="Manage tags"
		aria-expanded={isOpen}
	>
		<span class="tag-icon">🏷️</span>
		<span>Tags</span>
		{#if nodeTags.length > 0}
			<span class="tag-count">{nodeTags.length}</span>
		{/if}
	</button>

	{#if isOpen}
		<div class="tag-dropdown-panel" transition:slide={{ duration: 200 }}>
			<div class="tag-dropdown-header">Add Tags</div>

			<div class="tag-list">
				{#each Object.entries(PREDEFINED_TAGS) as [key, config] (key)}
					{@const isActive = nodeTags.includes(key)}
					<button
						type="button"
						class="tag-item"
						class:active={isActive}
						style:--tag-color={config.color}
						style:--tag-bg={config.bgColor}
						onclick={() => handleToggleTag(key)}
					>
						<span class="tag-item-check">{isActive ? '✓' : ''}</span>
						<span class="tag-item-label">{config.label}</span>
					</button>
				{/each}
			</div>

			<div class="tag-divider"></div>

			<div class="tag-custom">
				<input
					type="text"
					class="tag-custom-input"
					placeholder="Custom tag..."
					bind:value={customTagInput}
					onkeydown={handleKeydown}
				/>
				<button
					type="button"
					class="tag-custom-add"
					onclick={handleAddCustomTag}
					disabled={!customTagInput.trim()}
				>
					Add
				</button>
			</div>
		</div>
	{/if}
</div>

<style>
	.tag-dropdown-backdrop {
		position: fixed;
		inset: 0;
		z-index: 99;
		pointer-events: auto;
	}

	.tag-dropdown-container {
		position: relative;
		display: inline-block;
	}

	.tag-dropdown-trigger {
		display: inline-flex;
		align-items: center;
		gap: 4px;
		padding: 5px 10px;
		border: 1px solid var(--traek-toolbar-badge-border, rgba(255, 255, 255, 0.08));
		border-radius: 999px;
		background: var(--traek-toolbar-badge-bg, rgba(255, 255, 255, 0.06));
		color: var(--traek-toolbar-text, #cccccc);
		font-size: 12px;
		cursor: pointer;
		white-space: nowrap;
		transition:
			background 0.12s,
			border-color 0.12s;
		line-height: 1.4;
	}

	.tag-dropdown-trigger:hover {
		background: var(--traek-toolbar-badge-hover, rgba(255, 255, 255, 0.12));
		border-color: var(--traek-toolbar-badge-border-hover, rgba(255, 255, 255, 0.18));
	}

	.tag-dropdown-trigger:focus-visible {
		outline: 2px solid var(--traek-input-button-bg, #00d8ff);
		outline-offset: 2px;
	}

	.tag-icon {
		font-size: 13px;
		line-height: 1;
	}

	.tag-count {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		min-width: 16px;
		height: 16px;
		padding: 0 4px;
		border-radius: 999px;
		background: var(--traek-thought-tag-cyan, #00d8ff);
		color: #000;
		font-size: 10px;
		font-weight: 600;
		line-height: 1;
	}

	.tag-dropdown-panel {
		position: absolute;
		top: 100%;
		left: 0;
		margin-top: 4px;
		min-width: 200px;
		background: var(--traek-thought-panel-bg, rgba(22, 22, 22, 0.95));
		border: 1px solid var(--traek-thought-panel-border, #333333);
		border-radius: 12px;
		box-shadow: 0 8px 24px rgba(0, 0, 0, 0.4);
		backdrop-filter: blur(16px);
		z-index: 100;
		overflow: hidden;
	}

	.tag-dropdown-header {
		padding: 10px 12px 6px;
		font-size: 10px;
		font-weight: 600;
		letter-spacing: 0.5px;
		text-transform: uppercase;
		color: var(--traek-thought-header-muted, #666666);
	}

	.tag-list {
		display: flex;
		flex-direction: column;
		gap: 2px;
		padding: 4px 8px;
	}

	.tag-item {
		display: flex;
		align-items: center;
		gap: 8px;
		padding: 6px 8px;
		background: transparent;
		border: none;
		border-radius: 6px;
		color: var(--traek-thought-row-muted-2, #aaaaaa);
		font: inherit;
		font-size: 12px;
		text-align: left;
		cursor: pointer;
		transition:
			background 0.12s,
			color 0.12s;
	}

	.tag-item:hover {
		background: rgba(255, 255, 255, 0.06);
	}

	.tag-item.active {
		background: var(--tag-bg);
		color: var(--tag-color);
	}

	.tag-item-check {
		width: 16px;
		height: 16px;
		display: inline-flex;
		align-items: center;
		justify-content: center;
		border: 1px solid currentColor;
		border-radius: 3px;
		font-size: 10px;
		opacity: 0.7;
	}

	.tag-item.active .tag-item-check {
		opacity: 1;
	}

	.tag-item-label {
		flex: 1;
	}

	.tag-divider {
		height: 1px;
		margin: 6px 8px;
		background: var(--traek-thought-divider, rgba(255, 255, 255, 0.06));
	}

	.tag-custom {
		display: flex;
		gap: 6px;
		padding: 8px;
	}

	.tag-custom-input {
		flex: 1;
		padding: 6px 10px;
		background: rgba(255, 255, 255, 0.03);
		border: 1px solid var(--traek-thought-toggle-border, #555555);
		border-radius: 6px;
		color: var(--traek-textnode-text, #dddddd);
		font: inherit;
		font-size: 11px;
	}

	.tag-custom-input::placeholder {
		color: var(--traek-thought-row-muted-4, #666666);
	}

	.tag-custom-input:focus {
		outline: none;
		border-color: var(--traek-input-button-bg, #00d8ff);
	}

	.tag-custom-add {
		padding: 6px 12px;
		background: var(--traek-input-button-bg, #00d8ff);
		border: none;
		border-radius: 6px;
		color: var(--traek-input-button-text, #000000);
		font: inherit;
		font-size: 11px;
		font-weight: 600;
		cursor: pointer;
		transition:
			opacity 0.12s,
			transform 0.12s;
	}

	.tag-custom-add:hover:not(:disabled) {
		opacity: 0.9;
		transform: scale(1.02);
	}

	.tag-custom-add:disabled {
		opacity: 0.4;
		cursor: not-allowed;
	}
</style>

// packages/vue/src/tags/TagDropdown.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import type { TraekEngine } from '@traek/core';
import { getNodeTags, PREDEFINED_TAGS } from './tagUtils.js';

export interface TagDropdownProps {
	nodeId: string;
	engine: TraekEngine;
	onClose?: () => void;
}

const props = defineProps<TagDropdownProps>();

const customInput = ref('');

const currentTags = computed(() => {
	const node = props.engine.getNode(props.nodeId);
	return node ? getNodeTags(node) : [];
});

function toggleTag(tag: string) {
	const node = props.engine.getNode(props.nodeId);
	if (!node) return;
	const tags = getNodeTags(node);
	const next = tags.includes(tag) ? tags.filter((t) => t !== tag) : [...tags, tag];
	props.engine.updateNode(props.nodeId, { metadata: { x: 0, y: 0, ...node.metadata, tags: next } });
}

function addCustom() {
	const val = customInput.value.trim().toLowerCase().replace(/\s+/g, '-');
	if (!val) return;
	const node = props.engine.getNode(props.nodeId);
	if (!node) return;
	const tags = getNodeTags(node);
	if (!tags.includes(val)) {
		props.engine.updateNode(props.nodeId, {
			metadata: { x: 0, y: 0, ...node.metadata, tags: [...tags, val] }
		});
	}
	customInput.value = '';
}
</script>

<template>
	<div
		:style="{
			background: 'var(--traek-node-bg, #1a1a1a)',
			border: '1px solid var(--traek-node-border, #333)',
			borderRadius: '8px',
			padding: '12px',
			minWidth: '180px',
			boxShadow: '0 4px 16px rgba(0,0,0,0.4)'
		}"
	>
		<div :style="{ fontSize: '11px', color: '#666', marginBottom: '8px', fontWeight: 600 }">
			Tags
		</div>
		<div :style="{ display: 'flex', flexDirection: 'column', gap: '4px' }">
			<button
				v-for="[key, cfg] in Object.entries(PREDEFINED_TAGS)"
				:key="key"
				:style="{
					display: 'flex',
					alignItems: 'center',
					gap: '8px',
					padding: '4px 8px',
					borderRadius: '6px',
					border: 'none',
					background: currentTags.includes(key) ? cfg.bgColor : 'transparent',
					color: currentTags.includes(key) ? cfg.color : '#aaa',
					cursor: 'pointer',
					textAlign: 'left',
					fontSize: '12px'
				}"
				@click="toggleTag(key)"
			>
				<span
					:style="{
						width: '8px',
						height: '8px',
						borderRadius: '50%',
						background: cfg.color,
						flexShrink: 0
					}"
				/>
				{{ cfg.label }}
				<span
					v-if="currentTags.includes(key)"
					:style="{ marginLeft: 'auto', fontSize: '10px', opacity: 0.7 }"
				>
					✓
				</span>
			</button>
		</div>
		<div :style="{ display: 'flex', gap: '4px', marginTop: '8px' }">
			<input
				v-model="customInput"
				placeholder="Custom tag..."
				:style="{
					flex: 1,
					padding: '4px 8px',
					borderRadius: '6px',
					border: '1px solid #444',
					background: '#111',
					color: '#ddd',
					fontSize: '12px',
					outline: 'none'
				}"
				@keydown.enter="addCustom"
			/>
			<button
				:style="{
					padding: '4px 8px',
					borderRadius: '6px',
					border: 'none',
					background: '#333',
					color: '#ddd',
					cursor: 'pointer',
					fontSize: '12px'
				}"
				@click="addCustom"
			>
				Add
			</button>
		</div>
		<button
			v-if="onClose"
			:style="{
				display: 'block',
				width: '100%',
				marginTop: '8px',
				padding: '4px',
				borderRadius: '6px',
				border: '1px solid #333',
				background: 'transparent',
				color: '#666',
				cursor: 'pointer',
				fontSize: '11px'
			}"
			@click="onClose"
		>
			Close
		</button>
	</div>
</template>
